name: darkness_dungeon
description: RPG Game.

version: 1.3.6+11
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bonfire: ^3.0.0
  firebase_core: ^2.32.0
  flame_audio: ^2.0.5
  flame_splash_screen: ^0.1.0
  firebase_auth: ^4.20.0
  provider: ^6.1.2
  cloud_firestore:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.14
  auto_route: ^8.1.3

dev_dependencies:
  change_app_package_name: ^1.1.0

  test: any

#  flutter_launcher_icons: "^0.7.3"
#
#flutter_icons:
#  android: true
#  ios: true
#  image_path_android: "icone/icone_android.png"
#  image_path_ios: "icone/icone_ios.png"
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/emote/
    - assets/images/npc/
    - assets/images/enemy/
    - assets/images/enemy/goblin/
    - assets/images/enemy/imp/
    - assets/images/enemy/mini_boss/
    - assets/images/enemy/boss/
    - assets/images/player/
    - assets/images/items/
    - assets/images/tiled/
    - assets/audio/
    - resources/lang/en.json
    - resources/lang/es.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Normal
      fonts:
        - asset: fonts/font_pixel.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
